name: Build docker image
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:
    paths:
      - Dockerfile
  schedule:
    - cron: 0 18 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-primary-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-primary-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOTFILES_USER }}
          password: ${{ secrets.DOTFILES_TOKEN }}
      - name: Determine tag name (master)
        if: github.ref == 'refs/heads/master'
        run: |
          echo "PRIMARY_TAG=nightly" >> $GITHUB_ENV
      - name: Determine tag name (pull request)
        if: github.event_name == 'pull_request'
        run: |
          pr_num=`cat $GITHUB_EVENT_PATH | jq -r ".number"`
          echo "PRIMARY_TAG=pr-${pr_num}" >> $GITHUB_ENV
      - name: Determine tag name (tags)
        if: startsWith( github.ref, 'refs/tags/')
        id: determine_tag
        run: |
          tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
          echo "PRIMARY_TAG=${tag_name}" >> $GITHUB_ENV
          echo "EXTRA_OPTS=${EXTRA_OPTS}" >> $GITHUB_ENV
        env:
          EXTRA_OPTS: --tag rinx/devenv:stable --tag ghcr.io/rinx/devenv:stable
      - name: Build and Push
        run: |
          docker buildx build \
            --builder ${BUILDER} \
            --platforms ${PLATFORMS} \
            --tag rinx/devenv:${PRIMARY_TAG} \
            --tag ghcr.io/rinx/devenv:${PRIMARY_TAG} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache \
            ${EXTRA_OPTS} \
            --push
        env:
          DOCKER_BUILDKIT: 1
          PLATFORMS: linux/amd64
          BUILDER: ${{ steps.buildx.outputs.name }}
  build-java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-java8-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-java8-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOTFILES_USER }}
          password: ${{ secrets.DOTFILES_TOKEN }}
      - name: Determine tag name (master)
        if: github.ref == 'refs/heads/master'
        run: |
          echo "PRIMARY_TAG=nightly-java8" >> $GITHUB_ENV
      - name: Determine tag name (pull request)
        if: github.event_name == 'pull_request'
        run: |
          pr_num=`cat $GITHUB_EVENT_PATH | jq -r ".number"`
          echo "PRIMARY_TAG=pr-${pr_num}-java8" >> $GITHUB_ENV
      - name: Determine tag name (tags)
        if: startsWith( github.ref, 'refs/tags/')
        id: determine_tag
        run: |
          tag_name=`echo $GITHUB_REF | sed -e 's:^refs/tags/::'`
          echo "PRIMARY_TAG=${tag_name}-java8" >> $GITHUB_ENV
          echo "EXTRA_OPTS=${EXTRA_OPTS}" >> $GITHUB_ENV
        env:
          EXTRA_OPTS: --tag rinx/devenv:stable-java8 --tag ghcr.io/rinx/devenv:stable-java8
      - name: Build and Push
        run: |
          docker buildx build \
            --builder ${BUILDER} \
            --platforms ${PLATFORMS} \
            --tag rinx/devenv:${PRIMARY_TAG} \
            --tag ghcr.io/rinx/devenv:${PRIMARY_TAG} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache \
            --build-arg GRAALVM_JAVA_VERSION=java8 \
            ${EXTRA_OPTS} \
            --push
        env:
          DOCKER_BUILDKIT: 1
          PLATFORMS: linux/amd64
          BUILDER: ${{ steps.buildx.outputs.name }}
